kind: pipeline
type: docker
name: default

image_pull_secrets:
  - namely_pull_secrets

trigger:
  ref:
    include:
      - refs/heads/master
      - refs/pull/**
      - refs/tags/**


steps:

  - name: generate-tags
    image: registry.namely.land/namely/drone-docker-tag:1.4
    pull: true
    settings:
      mode: magic
      primary_tag_file: .primary_tag

  - name: compile
    image: registry.namely.land/namely/sbt:1.3.6-2.13.1
    commands:
      - export VERSION=`cat .primary_tag`
      - sbt + compile

  - name: publish
    image: registry.namely.land/namely/sbt:1.3.6-2.13.1
    commands:
      - export VERSION=`cat .primary_tag`
      - sbt ++2.12.8 publish ++2.13.1 publish
    environment:
      JFROG_USERNAME:
        from_secret: namely_jfrog_username
      JFROG_PASSWORD:
        from_secret: namely_jfrog_api_key
    when:
      ref:
        include:
          - refs/pull/**
          - refs/tags/**
